config/routes.rb
Bookie::Application.routes.draw do

  resource :user_session
  resource :account, :controller => 'users'
  resources :teams
  resources :divisions

  root to: "bets#scoreboard"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic

  attr_accessible :real_name, :email, :password, :password_confirmation

  has_many :bets,       :dependent => :delete_all
  has_many :comments,   :dependent => :delete_all
  has_one  :specialbet, :dependent => :destroy

  after_create :create_bets
  after_create :create_specialbet

  after_create  :update_prizes
  after_destroy :update_prizes
  after_update  :update_prizes

private

  def create_bets
    Match.all.each do |m|
      Bet.create( :user => self, :match => m )
    end
  end

  def create_specialbet
    Specialbet.create( :user => self )
  end

  def update_prizes
    Prize.jackpot(true)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'login', :only => [:new, :create]

  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  before_filter :require_admin, :only => [:register_payments]

  skip_before_filter :setup_scoreboard, :set_query_user, :only => [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end

  def register_payments
    User.update_all( "payment_received = 't'", {:id => params[:payment_received]} )
    redirect_to :controller => "/bets", :action => "scoreboard"
  end

end

app/views/users/_form.erb
<%= form.label :real_name, 'Dein Name' %> (wird anderen Spielern angezeigt)<br />
<%= form.text_field :real_name %><br />
<%= form.label :email, 'Email-Adresse' %> (wird zum Einloggen benötigt; wird niemandem angezeigt)<br />
<%= form.text_field :email %><br />
<br />
<%= form.label :password, form.object.new_record? ? 'Passwort' : "Passwort ändern" %><br />
<%= form.password_field :password %><br />
<%= form.label :password_confirmation, 'Passwort bestätigen' %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<%= form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Anmeldung zum Tippspiel</h1>

<%= form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <p>
    <%= render :partial => "form", :object => f %>
  </p>
  <p>
    <%= f.submit "Anmelden" %>
  </p>
<% end %>

<p>
  Nach der Anmeldung geht es sofort weiter zum Tippspiel.
  Bitte vergiss nicht, bald deinen Spieleinsatz zu entrichten.
</p>

app/views/users/show.html.erb
<p>
  <b>E-Mail:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>


<%= link_to 'Edit', edit_account_path %>