config/routes.rb
Bookie::Application.routes.draw do

  resource :user_session
  resource :account, :controller => 'users'
  resources :teams
  resources :divisions

  root to: "bets#scoreboard"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_greeting.html.erb
<h3><%=h current_time %></h3>

<p>
  <b>Hallo <%=h current_user.real_name %></b>, du hast
  <b><%=h @score_board.score_for(current_user) || '?' %>&nbsp;Punkte</b>
  und stehst damit auf <b>Rang <%=h @score_board.rank_for(current_user) || '?' %></b>.
</p>

<p><b>Zur Zeit im Pott: <%= link_to number_to_currency(Prize.jackpot), :controller => '/prizes', :action => 'index' %></b></p>

<p>Viel Spaß beim Tippen!</p><hr/>

<p style="text-align: center"><i>Nächste Begegnung</i></p>

<p style="text-align: center"><%= display(Match.next(1).first, :include_date => true) %></p>

app/views/shared/_hof.html.erb
<% unless @hof.results.empty? %>
<h3>Hall of Fame</h3>
<table style="margin:0.2em" cellspacing="7">
  <tr>
    <td><%= image_tag 'knight.jpg', :class => 'hofpic' %></td>
    <td valign="top"><b>Hoff-Verdienstkreuz am Bande:</b><br/>
      <%= hof_linker( @hof, :correct ) %> mit <%= @hof[:correct][0][:correct] %>
      korrekt getippten Ergebnissen.</td>
    <td align="center"><%= image_tag 'star_medal_gold_orange.png' %></td>
  </tr>
  <tr>
    <td><%= image_tag 'netzer_head.jpg', :class => 'hofpic' %></td>
    <td valign="top"><b>Günter-Netzer-Award:</b><br/>
      <%= hof_linker( @hof, :tendency ) %> mit <%= @hof[:tendency][0][:tendency] +
        @hof[:tendency][0][:correct] %> korrekt getippten Tendenzen.</td>
    <td align="center"><%= image_tag 'star_medal_silver_blue.png' %></td>
  </tr>
  <tr>
    <td><%= image_tag 'beckmann_head.jpg', :class => 'hofpic' %></td>
    <td valign="top"><b>Reinhold-Beckmann-Medaille:</b><br/>
      <%= hof_linker( @hof, :wrong ) %> mit <%= @hof[:wrong][0][:wrong] %>
      komplett falschen Tipps.</td>
    <td align="center"><%= image_tag 'poo.png' %></td>
  </tr>
</table>
<% end %>

app/views/shared/_matchnavi.html.erb
<ul id="navibar">
  <% for div in all_divisions %>
  <li><%= link_to_unless_current div.name, merge_uid( { :action =>
  'division', :id => div.id } ) %></li><% end %>
  <li><%= link_to_unless_current 'letzte vier',
  merge_uid( { :action => 'last' , :id => 4 } ), { :class => 'speciala' }  %></li>
  <li><%= link_to_unless_current 'kommende vier',
  merge_uid( { :action => 'next' , :id => 4 } ), { :class => 'speciala' }  %></li>
  <li><%= link_to_unless_current 'alle',
  merge_uid( { :action => 'list' } ), { :class => 'speciala' }  %></li>
  <li><%= link_to_unless_current 'Sondertipps',
  merge_uid( { :action => 'special' } ), { :class => 'specialb' } %></li>
</ul>
<div id="pageline"><hr style="display:none;"/></div>

app/views/shared/_navigation.html.erb
<h3>Menü</h3>
<%#<li style="background: red;"><a style="color:white;" href="ranks.html">Endergebnis</a></li>%>
<li><%= link_to 'Stammtisch', :controller => '/comments', :action => 'list' %></li>
<li><%= link_to 'Tippen', :controller => '/bets', :action => 'next', :id => 4 %></li>
<li><%= link_to 'Rangliste', :controller => '/bets', :action => 'scoreboard' %></li>
<li><%= link_to 'Gewinne', :controller => '/prizes', :action => 'index' %></li>
<% if current_user.admin %>
  <li><%= link_to 'Begegnungen', :controller => '/matches', :action => 'last', :id => 4 %></li>
  <li><%= link_to 'Mannschaften', teams_path %></li>
  <li><%= link_to 'Spielgruppen', divisions_path %></li>
  <!--<li><%#= link_to 'Konten', users_path</li>%>-->
<% end %>
<li style="background: #fdb;"><%= link_to 'Abmelden', user_session_path, :method => :delete %></li>

app/views/shared/_score_board.html.erb
<% if !@scoreboard.nil? %>
  <div id="quickscore">
    <h3>Top 5</h3>
    <table>
      <tr>
        <th>Rang</th> <th>Spieler</th> <th>Pkt.</th>
      </tr>
      <% for score in @scoreboard.slice(0..4) %>
        <tr>
          <td align="right"><%=h score[:rank] %></td>
          <td><%= link_to_user score[:user] %></td>
          <td align="right"><%=h score[:score] %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>