config/routes.rb
Bookie::Application.routes.draw do

  resource :user_session
  resource :account, :controller => 'users'
  resources :teams
  resources :divisions

  root to: "bets#scoreboard"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/user_sessions_controller.rb
# Taken from Authlogic example application
class UserSessionsController < ApplicationController

  layout 'login'

  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user,    :only => :destroy

  skip_before_filter :setup_scoreboard, :set_query_user
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    redirect_back_or_default new_user_session_url
  end

end

app/views/user_sessions/new.html.erb
<h1>Tippspiel Rezeption</h1>

<p>Bitte gib deine Email-Adresse und dein Passwort ein.</p>

<%= form_for @user_session, :url => user_session_path do |f| %>
  <%= f.error_messages %>
  <%= f.label :email, 'Email-Adresse' %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password, 'Passwort' %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.check_box :remember_me %><%= f.label :remember_me, 'Eingeloggt bleiben' %><br />
  <br />
  <%= f.submit "Einloggen" %>
<% end %>

<p>
  Noch nicht angemeldet? <%= link_to 'Hier klicken!', new_account_path %>
</p>